export enum FilterResourceRegex {
  ATTACHMENTS = '^attachments$',
  VOLUME_AGE = '^volume-age$',
  CPU = '^cpu$',
  NETWORK_IN = '^network-in$',
  NETWORK_OUT = '^network-out$',
  LAUNCH_TIME = '^launch-time$',
  INSTANCE_IDS = '^instance-ids$',
  DNS_NAME = '^dns-name$',
  DATABASE_CONNECTIONS = '^database-connections$',
  INSTANCES = '^instances$',
  ASSOCIATION_IDS = '^association-ids$',
  TAG = '^tag:.{1,128}$',
  LABEL = '^label:.{1,63}$',
  VOLUME_ID = '^volume-id$',
  INSTANCE_ID = '^instance-id$',
  DB_INSTANCE_IDENTIFIER = '^db-instance-identifier$',
  PUBLIC_IP = '^public-ip$',
  LOAD_BALANCER_NAME = '^load-balancer-name$',
  NAME = '^name$',
}
